// 種目一覧。id は記録に保存されるので、一度使った id は変えない・消さない。
// method: wr=重量×回数 bw=自重 assist=アシスト time=時間 cardio=有酸素
// eq: 器具（一覧の見出しに使う）
export const EQUIPMENT = [
  { id: 'barbell', name: 'バーベル' },
  { id: 'dumbbell', name: 'ダンベル' },
  { id: 'machine', name: 'マシン' },
  { id: 'smith', name: 'スミスマシン' },
  { id: 'cable', name: 'ケーブル' },
  { id: 'kettle', name: 'ケトルベル・その他' },
  { id: 'bw', name: '自重' },
  { id: 'cardio', name: '有酸素' },
];

// [id, 名前, 部位, 記録方式, 器具, 検索用の別名...]
const L = [
  // ---------------- 胸 ----------------
  ['ex_bench', 'ベンチプレス', 'chest', 'wr', 'barbell', 'bench', 'べんち'],
  ['ex_incline', 'インクラインベンチプレス', 'chest', 'wr', 'barbell', 'いんくらいんぷれす'],
  ['ex_decline_bench', 'デクラインベンチプレス', 'chest', 'wr', 'barbell'],
  ['ex_wide_bench', 'ワイドグリップベンチプレス', 'chest', 'wr', 'barbell'],
  ['ex_db_press', 'ダンベルプレス', 'chest', 'wr', 'dumbbell', 'だんべるべんち'],
  ['ex_incline_db_press', 'インクラインダンベルプレス', 'chest', 'wr', 'dumbbell'],
  ['ex_decline_db_press', 'デクラインダンベルプレス', 'chest', 'wr', 'dumbbell'],
  ['ex_fly', 'ダンベルフライ', 'chest', 'wr', 'dumbbell', 'ふらい'],
  ['ex_incline_fly', 'インクラインダンベルフライ', 'chest', 'wr', 'dumbbell'],
  ['ex_pullover', 'ダンベルプルオーバー', 'chest', 'wr', 'dumbbell', 'ぷるおーばー'],
  ['ex_squeeze_press', 'スクイーズプレス', 'chest', 'wr', 'dumbbell'],
  ['ex_chest_press', 'チェストプレス', 'chest', 'wr', 'machine', 'ちぇすと'],
  ['ex_incline_chest_press', 'インクラインチェストプレス', 'chest', 'wr', 'machine'],
  ['ex_pec_fly', 'ペックフライ', 'chest', 'wr', 'machine', 'バタフライ', 'ぺっくでっく', 'ペックデック'],
  ['ex_smith_bench', 'スミスマシンベンチプレス', 'chest', 'wr', 'smith'],
  ['ex_smith_incline', 'スミスマシンインクラインプレス', 'chest', 'wr', 'smith'],
  ['ex_cable_cross', 'ケーブルクロスオーバー', 'chest', 'wr', 'cable', 'くろすおーばー'],
  ['ex_low_cable_fly', 'ローケーブルフライ', 'chest', 'wr', 'cable', 'ロープーリーフライ'],
  ['ex_high_cable_fly', 'ハイケーブルフライ', 'chest', 'wr', 'cable', 'ハイプーリーフライ'],
  ['ex_pushup', '腕立て伏せ', 'chest', 'bw', 'bw', 'うでたて', 'プッシュアップ', 'push up'],
  ['ex_knee_pushup', '膝つき腕立て伏せ', 'chest', 'bw', 'bw', 'ひざつき', 'ニープッシュアップ'],
  ['ex_wide_pushup', 'ワイドプッシュアップ', 'chest', 'bw', 'bw', '腕立て'],
  ['ex_incline_pushup', 'インクラインプッシュアップ', 'chest', 'bw', 'bw', '腕立て'],
  ['ex_decline_pushup', 'デクラインプッシュアップ', 'chest', 'bw', 'bw', '腕立て'],
  ['ex_archer_pushup', 'アーチャープッシュアップ', 'chest', 'bw', 'bw', '腕立て'],
  ['ex_clap_pushup', 'クラッププッシュアップ', 'chest', 'bw', 'bw', '腕立て'],
  ['ex_chest_dips', 'チェストディップス', 'chest', 'bw', 'bw', 'でぃっぷす'],

  // ---------------- 背中 ----------------
  ['ex_deadlift', 'デッドリフト', 'back', 'wr', 'barbell', 'でっど'],
  ['ex_row', 'ベントオーバーロウ', 'back', 'wr', 'barbell', 'ろう', 'べんとおーばー'],
  ['ex_pendlay_row', 'ペンドレイロウ', 'back', 'wr', 'barbell'],
  ['ex_tbar_row', 'Tバーロウ', 'back', 'wr', 'barbell', 'てぃーばー'],
  ['ex_rack_pull', 'ラックプル', 'back', 'wr', 'barbell'],
  ['ex_bb_shrug', 'バーベルシュラッグ', 'back', 'wr', 'barbell', 'しゅらっぐ', '僧帽筋'],
  ['ex_one_arm_row', 'ワンハンドダンベルロウ', 'back', 'wr', 'dumbbell', 'わんはんどろう', 'ダンベルロウ'],
  ['ex_db_row', 'ダンベルベントオーバーロウ', 'back', 'wr', 'dumbbell'],
  ['ex_db_shrug', 'ダンベルシュラッグ', 'back', 'wr', 'dumbbell', '僧帽筋'],
  ['ex_lat', 'ラットプルダウン', 'back', 'wr', 'machine', 'らっと'],
  ['ex_narrow_lat', 'ナローグリップラットプルダウン', 'back', 'wr', 'machine', 'らっと'],
  ['ex_reverse_lat', 'リバースグリップラットプルダウン', 'back', 'wr', 'machine', 'らっと'],
  ['ex_seated_row', 'シーテッドロウ', 'back', 'wr', 'machine', 'ろーいんぐ'],
  ['ex_machine_row', 'マシンロウ', 'back', 'wr', 'machine', 'ろーいんぐ'],
  ['ex_back_ext_machine', 'バックエクステンション（マシン）', 'back', 'wr', 'machine', '背筋'],
  ['ex_achin', 'アシスト懸垂', 'back', 'assist', 'machine', 'あしすと', 'アシストチンニング'],
  ['ex_cable_row', 'ケーブルロウ', 'back', 'wr', 'cable', 'ろーぷーりー'],
  ['ex_straight_pulldown', 'ストレートアームプルダウン', 'back', 'wr', 'cable'],
  ['ex_chin', '懸垂', 'back', 'bw', 'bw', 'けんすい', 'チンニング', 'プルアップ'],
  ['ex_chinup', '逆手懸垂', 'back', 'bw', 'bw', 'さかてけんすい', 'チンアップ'],
  ['ex_inverted_row', '斜め懸垂', 'back', 'bw', 'bw', 'ななめけんすい', 'インバーテッドロウ'],
  ['ex_back_ext', 'バックエクステンション', 'back', 'bw', 'bw', '背筋', 'はいきん'],
  ['ex_superman', 'スーパーマン', 'back', 'bw', 'bw', '背筋'],

  // ---------------- 肩 ----------------
  ['ex_spress', 'ショルダープレス', 'shoulder', 'wr', 'barbell', 'しょるだー', 'オーバーヘッドプレス'],
  ['ex_military', 'ミリタリープレス', 'shoulder', 'wr', 'barbell'],
  ['ex_bnp', 'ビハインドネックプレス', 'shoulder', 'wr', 'barbell'],
  ['ex_upright_row', 'アップライトロウ', 'shoulder', 'wr', 'barbell'],
  ['ex_db_spress', 'ダンベルショルダープレス', 'shoulder', 'wr', 'dumbbell', 'しょるだー'],
  ['ex_arnold', 'アーノルドプレス', 'shoulder', 'wr', 'dumbbell'],
  ['ex_side', 'サイドレイズ', 'shoulder', 'wr', 'dumbbell', 'さいど', 'ラテラルレイズ'],
  ['ex_front', 'フロントレイズ', 'shoulder', 'wr', 'dumbbell', 'ふろんと'],
  ['ex_rear', 'リアレイズ', 'shoulder', 'wr', 'dumbbell', 'りあ', 'リアデルト'],
  ['ex_incline_side', 'インクラインサイドレイズ', 'shoulder', 'wr', 'dumbbell'],
  ['ex_db_upright', 'ダンベルアップライトロウ', 'shoulder', 'wr', 'dumbbell'],
  ['ex_machine_spress', 'マシンショルダープレス', 'shoulder', 'wr', 'machine', 'しょるだー'],
  ['ex_machine_side', 'マシンサイドレイズ', 'shoulder', 'wr', 'machine'],
  ['ex_rear_delt_fly', 'リアデルトフライ', 'shoulder', 'wr', 'machine', 'りあ'],
  ['ex_smith_spress', 'スミスマシンショルダープレス', 'shoulder', 'wr', 'smith'],
  ['ex_cable_side', 'ケーブルサイドレイズ', 'shoulder', 'wr', 'cable'],
  ['ex_face_pull', 'フェイスプル', 'shoulder', 'wr', 'cable', 'ふぇいす'],
  ['ex_cable_rear', 'ケーブルリアレイズ', 'shoulder', 'wr', 'cable'],
  ['ex_pike_pushup', 'パイクプッシュアップ', 'shoulder', 'bw', 'bw', '腕立て'],
  ['ex_hspu', '逆立ち腕立て伏せ', 'shoulder', 'bw', 'bw', 'さかだち', 'ハンドスタンドプッシュアップ'],
  ['ex_handstand', '壁倒立', 'shoulder', 'time', 'bw', 'かべとうりつ', 'ハンドスタンド'],

  // ---------------- 脚・お尻 ----------------
  ['ex_squat', 'スクワット', 'leg', 'wr', 'barbell', 'すくわっと', 'バーベルスクワット'],
  ['ex_front_squat', 'フロントスクワット', 'leg', 'wr', 'barbell'],
  ['ex_rdl', 'ルーマニアンデッドリフト', 'leg', 'wr', 'barbell', 'るーまにあん', 'RDL'],
  ['ex_sldl', 'スティッフレッグデッドリフト', 'leg', 'wr', 'barbell'],
  ['ex_hip_thrust', 'ヒップスラスト', 'leg', 'wr', 'barbell', 'お尻', 'おしり', 'ひっぷ'],
  ['ex_bb_lunge', 'バーベルランジ', 'leg', 'wr', 'barbell'],
  ['ex_sumo_dl', 'スモウデッドリフト', 'leg', 'wr', 'barbell', 'すもう'],
  ['ex_goblet', 'ゴブレットスクワット', 'leg', 'wr', 'dumbbell'],
  ['ex_db_squat', 'ダンベルスクワット', 'leg', 'wr', 'dumbbell'],
  ['ex_bulgarian', 'ブルガリアンスクワット', 'leg', 'wr', 'dumbbell', 'ぶるがりあん', 'スプリットスクワット'],
  ['ex_db_lunge', 'ダンベルランジ', 'leg', 'wr', 'dumbbell'],
  ['ex_db_rdl', 'ダンベルルーマニアンデッドリフト', 'leg', 'wr', 'dumbbell'],
  ['ex_step_up', 'ステップアップ', 'leg', 'wr', 'dumbbell', '踏み台'],
  ['ex_legpress', 'レッグプレス', 'leg', 'wr', 'machine', 'れっぐ'],
  ['ex_leg_ext', 'レッグエクステンション', 'leg', 'wr', 'machine', 'れっぐえくすて', '太もも前'],
  ['ex_leg_curl', 'レッグカール', 'leg', 'wr', 'machine', 'ハムストリング', '太もも裏', 'ライイングレッグカール'],
  ['ex_seated_leg_curl', 'シーテッドレッグカール', 'leg', 'wr', 'machine', '太もも裏'],
  ['ex_hack_squat', 'ハックスクワット', 'leg', 'wr', 'machine'],
  ['ex_adduction', 'アダクション', 'leg', 'wr', 'machine', '内もも', 'うちもも', 'アダクター'],
  ['ex_abduction', 'アブダクション', 'leg', 'wr', 'machine', '外もも', 'お尻', 'アブダクター'],
  ['ex_glute_kickback', 'グルートキックバック', 'leg', 'wr', 'machine', 'お尻', 'おしり'],
  ['ex_calf_raise_m', 'カーフレイズ（マシン）', 'leg', 'wr', 'machine', 'ふくらはぎ', 'かーふ'],
  ['ex_seated_calf', 'シーテッドカーフレイズ', 'leg', 'wr', 'machine', 'ふくらはぎ'],
  ['ex_smith', 'スミスマシンスクワット', 'leg', 'wr', 'smith', 'すみす'],
  ['ex_smith_lunge', 'スミスマシンランジ', 'leg', 'wr', 'smith'],
  ['ex_cable_kickback', 'ケーブルキックバック', 'leg', 'wr', 'cable', 'お尻'],
  ['ex_bw_squat', '自重スクワット', 'leg', 'bw', 'bw', 'じじゅう', 'エアスクワット'],
  ['ex_wide_squat', 'ワイドスクワット', 'leg', 'bw', 'bw', 'スモウスクワット'],
  ['ex_jump_squat', 'ジャンプスクワット', 'leg', 'bw', 'bw'],
  ['ex_lunge', 'ランジ', 'leg', 'bw', 'bw', 'らんじ'],
  ['ex_side_lunge', 'サイドランジ', 'leg', 'bw', 'bw'],
  ['ex_bw_bulgarian', 'ブルガリアンスクワット（自重）', 'leg', 'bw', 'bw'],
  ['ex_pistol', '片足スクワット', 'leg', 'bw', 'bw', 'かたあし', 'ピストルスクワット'],
  ['ex_hip_lift', 'ヒップリフト', 'leg', 'bw', 'bw', 'お尻', 'グルートブリッジ'],
  ['ex_single_hip_lift', '片足ヒップリフト', 'leg', 'bw', 'bw', 'お尻'],
  ['ex_calf_raise', 'カーフレイズ', 'leg', 'bw', 'bw', 'ふくらはぎ', 'かーふ'],
  ['ex_wall_sit', '空気椅子', 'leg', 'time', 'bw', 'くうきいす', 'ウォールシット'],
  ['ex_donkey_kick', 'ドンキーキック', 'leg', 'bw', 'bw', 'お尻'],

  // ---------------- 腕 ----------------
  ['ex_bb_curl', 'バーベルカール', 'arm', 'wr', 'barbell', '二頭', 'にとう'],
  ['ex_ez_curl', 'EZバーカール', 'arm', 'wr', 'barbell', '二頭'],
  ['ex_preacher', 'プリーチャーカール', 'arm', 'wr', 'barbell', '二頭'],
  ['ex_close_bench', 'ナローベンチプレス', 'arm', 'wr', 'barbell', '三頭', 'さんとう', 'クローズグリップ'],
  ['ex_skull', 'ライイングトライセプスエクステンション', 'arm', 'wr', 'barbell', '三頭', 'スカルクラッシャー'],
  ['ex_curl', 'アームカール', 'arm', 'wr', 'dumbbell', 'かーる', 'ダンベルカール', '二頭'],
  ['ex_hammer', 'ハンマーカール', 'arm', 'wr', 'dumbbell', 'はんまー'],
  ['ex_incline_curl', 'インクラインダンベルカール', 'arm', 'wr', 'dumbbell', '二頭'],
  ['ex_concentration', 'コンセントレーションカール', 'arm', 'wr', 'dumbbell', '二頭'],
  ['ex_french', 'フレンチプレス', 'arm', 'wr', 'dumbbell', '三頭', 'オーバーヘッドエクステンション'],
  ['ex_kickback', 'キックバック', 'arm', 'wr', 'dumbbell', '三頭', 'トライセプスキックバック'],
  ['ex_wrist_curl', 'リストカール', 'arm', 'wr', 'dumbbell', '前腕', 'ぜんわん'],
  ['ex_reverse_wrist', 'リバースリストカール', 'arm', 'wr', 'dumbbell', '前腕'],
  ['ex_reverse_curl', 'リバースカール', 'arm', 'wr', 'dumbbell', '前腕'],
  ['ex_machine_curl', 'マシンカール', 'arm', 'wr', 'machine', '二頭'],
  ['ex_machine_tri', 'マシントライセプスエクステンション', 'arm', 'wr', 'machine', '三頭'],
  ['ex_pushdown', 'プレスダウン', 'arm', 'wr', 'cable', 'ぷれすだうん', '三頭', 'トライセプスプレスダウン'],
  ['ex_rope_pushdown', 'ロープ プレスダウン', 'arm', 'wr', 'cable', '三頭'],
  ['ex_cable_curl', 'ケーブルカール', 'arm', 'wr', 'cable', '二頭'],
  ['ex_overhead_cable', 'オーバーヘッドケーブルエクステンション', 'arm', 'wr', 'cable', '三頭'],
  ['ex_dips', 'ディップス', 'arm', 'bw', 'bw', 'でぃっぷす', '三頭'],
  ['ex_bench_dips', 'ベンチディップス', 'arm', 'bw', 'bw', '三頭'],
  ['ex_diamond_pushup', 'ダイヤモンドプッシュアップ', 'arm', 'bw', 'bw', '三頭', '腕立て'],

  // ---------------- 腹 ----------------
  ['ex_crunch', 'クランチ', 'abs', 'bw', 'bw', 'くらんち', '腹筋'],
  ['ex_situp', 'シットアップ', 'abs', 'bw', 'bw', '腹筋', '上体起こし'],
  ['ex_legraise', 'レッグレイズ', 'abs', 'bw', 'bw', 'れっぐれいず', '腹筋'],
  ['ex_hanging_legraise', 'ハンギングレッグレイズ', 'abs', 'bw', 'bw', '腹筋'],
  ['ex_knee_raise', 'ニーレイズ', 'abs', 'bw', 'bw', '腹筋'],
  ['ex_reverse_crunch', 'リバースクランチ', 'abs', 'bw', 'bw', '腹筋'],
  ['ex_bicycle', 'バイシクルクランチ', 'abs', 'bw', 'bw', '腹筋', 'ツイストクランチ'],
  ['ex_russian_twist', 'ロシアンツイスト', 'abs', 'bw', 'bw', '腹斜筋'],
  ['ex_v_up', 'Vアップ', 'abs', 'bw', 'bw', '腹筋'],
  ['ex_mountain', 'マウンテンクライマー', 'abs', 'bw', 'bw'],
  ['ex_heel_touch', 'ヒールタッチ', 'abs', 'bw', 'bw', '腹斜筋'],
  ['ex_dead_bug', 'デッドバグ', 'abs', 'bw', 'bw'],
  ['ex_dragon_flag', 'ドラゴンフラッグ', 'abs', 'bw', 'bw'],
  ['ex_abroller', 'アブローラー', 'abs', 'bw', 'bw', 'あぶろーらー', '腹筋ローラー'],
  ['ex_plank', 'プランク', 'abs', 'time', 'bw', 'ぷらんく'],
  ['ex_side_plank', 'サイドプランク', 'abs', 'time', 'bw'],
  ['ex_hollow', 'ホロウボディホールド', 'abs', 'time', 'bw'],
  ['ex_cable_crunch', 'ケーブルクランチ', 'abs', 'wr', 'cable', '腹筋'],
  ['ex_ab_machine', 'アブドミナルクランチ', 'abs', 'wr', 'machine', '腹筋マシン'],
  ['ex_torso_rot', 'トーソローテーション', 'abs', 'wr', 'machine', '腹斜筋'],
  ['ex_side_bend', 'ダンベルサイドベンド', 'abs', 'wr', 'dumbbell', '腹斜筋'],
  ['ex_kb_swing', 'ケトルベルスイング', 'leg', 'wr', 'kettle', 'けとる'],
  ['ex_farmer', 'ファーマーズウォーク', 'back', 'wr', 'kettle', '握力'],

  // ---------------- 有酸素 ----------------
  ['ex_walk', 'ウォーキング', 'cardio', 'cardio', 'cardio', 'あるく', '散歩'],
  ['ex_run', 'ランニング', 'cardio', 'cardio', 'cardio', 'はしる', 'ジョギング'],
  ['ex_treadmill', 'トレッドミル', 'cardio', 'cardio', 'cardio', 'ランニングマシン'],
  ['ex_incline_walk', '傾斜ウォーキング', 'cardio', 'cardio', 'cardio', 'けいしゃ', 'トレッドミル'],
  ['ex_bike', 'エアロバイク', 'cardio', 'cardio', 'cardio', 'ばいく'],
  ['ex_cycling', 'サイクリング', 'cardio', 'cardio', 'cardio', '自転車', 'じてんしゃ'],
  ['ex_cross', 'クロストレーナー', 'cardio', 'cardio', 'cardio', 'エリプティカル'],
  ['ex_stair', 'ステアクライマー', 'cardio', 'cardio', 'cardio', '階段', 'かいだん'],
  ['ex_rowing', 'ローイングマシン', 'cardio', 'cardio', 'cardio', 'ボート漕ぎ'],
  ['ex_swim', '水泳', 'cardio', 'cardio', 'cardio', 'すいえい', 'プール'],
  ['ex_rope', '縄跳び', 'cardio', 'cardio', 'cardio', 'なわとび'],
  ['ex_hiit', 'HIIT', 'cardio', 'cardio', 'cardio', 'ひいと', 'インターバル', 'タバタ'],
  ['ex_burpee', 'バーピー', 'cardio', 'cardio', 'cardio', 'ばーぴー'],
  ['ex_step', '踏み台昇降', 'cardio', 'cardio', 'cardio', 'ふみだい'],
  ['ex_hike', 'ハイキング・登山', 'cardio', 'cardio', 'cardio', 'とざん'],
  ['ex_dance', 'ダンス・エアロビクス', 'cardio', 'cardio', 'cardio'],
  ['ex_boxing', 'ボクササイズ', 'cardio', 'cardio', 'cardio', 'ボクシング', 'キックボクシング'],
];

export const EXERCISES = L.map(([id, name, part, method, eq, ...alias]) => ({ id, name, part, method, eq, alias }));
